# Generated by Django 4.1.7 on 2023-03-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование курса/Course name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='О курсе/Description')),
                ('is_available', models.BooleanField(blank=True, null=True, verbose_name='Доступен/Available')),
            ],
        ),
    ]
